#!/bin/bash -eu

. "$plugin_dir/functions"

install_java_plugin_functions
install_java_control_functions
write_java_opts
install_java_agent

if java_app_configured; then
    create_app_skel
    install_app
    write_config
    write_start_control
fi

write_control

