#!/bin/sh
set -u
set -e

pidfile=$genapp_dir/app_pid
if [ -e $pidfile ]; then
    pid=`cat $pidfile`
    kill -3 $pid
    echo "Sent SIGQUIT to $pid"
else
    echo "Cannot find pid file"
    exit 1
fi
