#!/bin/bash
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config
. $control_dir/java/functions

java_opts="$(java_opts $control_dir)"

exec bash -c "
$java \
   $java_opts \
  -Djava.io.tmpdir=$tmp_dir \
  -Dapp.port=$port \
  -cp \"$classpath\" \
  $class \
  $args
"
